= Maven Shade Plugin - Extra Transformers
:linkattrs:
:author:                Andres Almiray
:project-owner:         kordamp
:project-repo:          maven
:project-name:          maven-shade-ext-transformers
:project-group:         org.kordamp.shade
:project-version:       1.3.0
:source-highlighter:    coderay
:coderay-linenums-mode: inline

image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

Additional transformers for http://maven.apache.org/plugins/maven-shade-plugin/[maven-shade-plugin].
Some of the provided transformers are based on code contributed to the
https://github.com/johnrengelman/shadow[Gradle's Shadow plugin] originating from the
https://github.com/griffon/griffon[Griffon] codebase.

== Configuration

You must add `{project-name}` as a dependency to the the `maven-shade-plugin`

[source,xml,linenums]
[subs="attributes,verbatim"]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.2.4</version>
            <configuration>
                <!-- configure transformers -->
            </configuration>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                </execution>
            </executions>
            <dependencies>
                <dependency>
                    <groupId>{project-package}</groupId>
                    <artifactId>{project-name}</artifactId>
                    <version>{project-version}</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
----

Now specify transformers as needed inside the plugin's `configuration` section.

== Transformers

The following transformers are available in version {version}:

=== ServicesResourceTransformer

This transformer performs the same task as `org.apache.maven.plugins.shade.resource.ServicesResourceTransformer` however
it exposes a configurable `path` property, where as the original will always transfom `'META-INF/services'`.

The following example shows the configuration required for processing files in a Griffon application project

[source,xml,linenums]
[subs="attributes,verbatim"]
----
<configuration>
    <transformer implementation="org.kordamp.shade.resources.ServicesResourceTransformer">
        <path>META-INF/griffon</path>
    </transformer>
</configuration>
----

.Properties
[cols="3*",options="header"]
|===
| Name | Type   | Default
| path | String | `META-INF/services`
|===

=== PropertiesFileTransformer

This transformer can merge properties files using a few strategies when duplicate keys are found. It will automatically
merge properties files ending with +.properties+ using +first+ as default merge strategy.

The following example shows the configuration required for processing files in a Griffon application project:

[source,xml,linenums]
[subs="attributes,verbatim"]
----
<configuration>
    <transformer implementation="org.kordamp.shade.resources.PropertiesFileTransformer">
        <paths>
            <path>META-INF/editors/java.beans.PropertyEditor</path>
        </paths>
    </transformer>
</configuration>
----

.Properties
[cols="4*",options="header"]
|===
| Name           | Type                     | Default | Notes
| mappings       | List<Map<String,String>> |         | takes precedence over +paths+
| paths          | List<String>             |         |
| mergeStrategy  | String                   | `first` | valid values are `first`, `append`, `latest`
| mergeSeparator | String                   | `,`     | used when `mergeStrategy = append`
|===
